const {
	VITE_AUTH_API_URL,
	VITE_CF_SPACE_ID,
	VITE_CF_CONTENT_DELIVERY_API_ACCESS_TOKEN,
	VITE_CF_LOCALIZED_PROPERTIES_ID,
} = import.meta.env;

export {
	VITE_AUTH_API_URL,
	VITE_CF_SPACE_ID,
	VITE_CF_CONTENT_DELIVERY_API_ACCESS_TOKEN,
	VITE_CF_LOCALIZED_PROPERTIES_ID,
};
