const {
	VITE_AUTH_API_URL,
	VITE_CF_SPACE_ID,
	VITE_CF_CONTENT_DELIVERY_API_ACCESS_TOKEN,
	VITE_CF_LOCALIZED_PROPERTIES_ID,
} = import.meta.env;

const CF_SPACE_ID = VITE_CF_SPACE_ID;
const CF_CONTENT_DELIVERY_API_ACCESS_TOKEN = VITE_CF_CONTENT_DELIVERY_API_ACCESS_TOKEN;
const CF_LOCALIZED_PROPERTIES_ID = VITE_CF_LOCALIZED_PROPERTIES_ID;

export {
	VITE_AUTH_API_URL,
	CF_SPACE_ID,
	CF_CONTENT_DELIVERY_API_ACCESS_TOKEN,
	CF_LOCALIZED_PROPERTIES_ID,
};
