const {
	VITE_AUTH_API_URL,
	VITE_CF_SPACE_ID,
	VITE_CF_CONTENT_DELIVERY_API_ACCESS_TOKEN,
	VITE_CF_LOCALIZED_PROPERTIES_ID,
} = import.meta.env;

const AWS_USER_POOL_ID = 'eu-north-1_xtrp2je9J';
const AWS_USER_POOL_APP_CLIENT_ID = 'ggh1cn1rkigatuca23t1g6fda';
const AWS_IDENTOTY_POOL_ID = 'eu-north-1:a9452216-890e-44d9-bce4-abd23523e605';

const CF_SPACE_ID = VITE_CF_SPACE_ID;
const CF_CONTENT_DELIVERY_API_ACCESS_TOKEN = VITE_CF_CONTENT_DELIVERY_API_ACCESS_TOKEN;
const CF_LOCALIZED_PROPERTIES_ID = VITE_CF_LOCALIZED_PROPERTIES_ID;

export {
	VITE_AUTH_API_URL,
	AWS_IDENTOTY_POOL_ID,
	AWS_USER_POOL_ID,
	AWS_USER_POOL_APP_CLIENT_ID,
	CF_SPACE_ID,
	CF_CONTENT_DELIVERY_API_ACCESS_TOKEN,
	CF_LOCALIZED_PROPERTIES_ID,
};
