projects:
  tictactoe:
    schemaPath: apps/web/src/graphql/schema.json
    includes:
      - apps/web/src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: apps/web/src/graphql/api.ts
        docsFilePath: apps/web/src/graphql
extensions:
  amplify:
    version: 3
