projects:
  tictactoe:
    schemaPath: apps/web/graphql/schema.json
    includes:
      - apps/web/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: apps/web/graphql/api.ts
        docsFilePath: apps/web/graphql
