name: CI

concurrency: production

on:
    pull_request:
        types: [opened, synchronize]
    push:
        branches:
            - '*'

jobs:
    validate-commit-message:
        name: Validate commit message
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Validate Commit Message
              uses: webiny/action-conventional-commits@v1.1.0

    log-env-variable:
        name: Log Env Variable
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Log Environment Variable
              env:
                  USERNAME: ${{ secrets.VITE_USERNAME }}
              run: |
                  echo "username: $USERNAME"

    run-tests:
        name: Run Tests
        needs: validate-commit-message
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 18.17.0

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install dependencies
              run: yarn install

            - name: Run Jest tests
              run: yarn test

            - name: Save test results
              uses: actions/upload-artifact@v2
              with:
                  name: test-results
                  path: ./coverage
