name: Validate Commit Messages

on:
    push:
        branches-ignore:
            - main # Ignore the main branch, adjust as needed
    pull_request:
        types: [opened, synchronize]

jobs:
    validate-commit-message:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Validate Commit Message
              uses: webiny/action-conventional-commits@v1.1.0
