name: CI

on:
    pull_request:
        types: [opened, synchronize]
    push:
        branches:
            - main

jobs:
    validate-commit-message:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Validate Commit Message
              uses: webiny/action-conventional-commits@v1.1.0

    run-tests:
        needs: validate-commit-message
        runs-on: ubuntu-latest

        steps:
            - uses: ./shared/steps.yml

            - name: Run Jest tests
              run: yarn test

            - name: Save test results
              uses: actions/upload-artifact@v2
              with:
                  name: test-results
                  path: ./coverage
