name: Release

on:
    workflow_run:
        workflows: ['Commit Validation']
        types:
            - completed
    push:
        branches:
            - 'main'

permissions:
    contents: write

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        environment: development
        if: github.event.workflow_run.conclusion == 'success'

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 18.17.0

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install dependencies
              run: yarn install

            - name: Apply Versioning
              run: npx semantic-release
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
