name: Release

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node and Yarn
              uses: ./shared/node-yarn.yml

            - name: Release
              run: npx semantic-release
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
